export const MOONLIGHT_SCHOLAR_SESSION_COOKIE = "lighthouse_moonlight_scholar_session";
export const MOONLIGHT_SCHOLAR_LOCAL_SESSION_COOKIE = "lh_moonlight_scholar_session";
export const MOONLIGHT_SCHOLAR_SESSION_COOKIE_NAMES = [MOONLIGHT_SCHOLAR_SESSION_COOKIE] as const;
export const MOONLIGHT_SCHOLAR_SESSION_CLEAR_COOKIE_NAMES = [
  MOONLIGHT_SCHOLAR_SESSION_COOKIE,
  MOONLIGHT_SCHOLAR_LOCAL_SESSION_COOKIE,
] as const;
export const MOONLIGHT_SCHOLAR_SESSION_MAX_AGE_SECONDS = 15 * 60;
